# Generated by Django 4.0.5 on 2022-06-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_match_bet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='team',
            field=models.CharField(choices=[('MB', 'Mirabooka Bucks'), ('MH', 'Melville Heat'), ('NK', 'North Perth Knicks'), ('WW', 'Willetton Wizards'), ('AM', 'Admin')], default='MB', max_length=2),
        ),
    ]
