# Generated by Django 4.0.5 on 2022-06-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_alter_customuser_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(choices=[('MB', 'Mirabooka Bucks'), ('MH', 'Melville Heat'), ('NK', 'North Perth Knicks'), ('WW', 'Willetton Wizards'), ('', '')], default='', max_length=2),
        ),
    ]
