# Generated by Django 4.0.5 on 2022-06-16 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0005_team_remove_match_players_alter_match_points_awarded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='bets.team'),
        ),
    ]
