# Generated by Django 4.0.5 on 2022-06-16 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0006_alter_customuser_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='winner', to='bets.team'),
        ),
    ]
