# Generated by Django 4.0.5 on 2022-06-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0007_alter_match_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(null=True, related_name='teams', to='bets.team'),
        ),
    ]
