# Generated by Django 4.0.5 on 2022-06-16 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0009_alter_match_teams_alter_match_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='choice', to='bets.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='teams', to='bets.team'),
        ),
    ]
