# Generated by Django 4.0.5 on 2022-06-17 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0010_bet_choice_alter_match_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='choice', to='bets.team'),
        ),
    ]
