# Generated by Django 4.0.5 on 2022-06-18 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0013_alter_customuser_options_alter_match_points_awarded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={'ordering': ['-amount']},
        ),
    ]
